services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=hris'
      - 'POSTGRES_PASSWORD=hris_password'
      - 'POSTGRES_USER=hris_user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hris
      - SPRING_DATASOURCE_USERNAME=hris_user
      - SPRING_DATASOURCE_PASSWORD=hris_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
      - SPRING_FLYWAY_VALIDATE_ON_MIGRATE=true
      - JWT_SECRET=hris_jwt_secret_key_2024_very_long_secure_key_for_jwt_tokens
      - JWT_EXPIRATION=86400000
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SERVER_PORT=8081

volumes:
  postgres_data:
  redis_data:
