-- Insert Indonesian cities with IATA codes
INSERT INTO cities (city_code, city_name, province_name, is_active) VALUES
('BTJ', 'Banda Aceh', 'Aceh', true),
('DPS', 'Denpasar', 'Bali', true),
('PGK', 'Pangkal Pinang', 'Bangka Belitung', true),
('BKS', 'Bengkulu', 'Bengkulu', true),
('SRG', 'Semarang', 'Central Java', true),
('PKY', 'Palangkaraya', 'Central Kalimantan', true),
('PLW', 'Palu', 'Central Sulawesi', true),
('BWX', 'Banyuwangi', 'East Java', true),
('JBB', 'Jember', 'East Java', true),
('DHX', 'Kediri', 'East Java', true),
('MLG', 'Malang', 'East Java', true),
('SUB', 'Surabaya', 'East Java', true),
('AAP', 'Samarinda', 'East Kalimantan', true),
('GTO', 'Gorontalo', 'Gorontalo', true),
('CGK', 'Jakarta', 'Jakarta', true),
('DJB', 'Jambi', 'Jambi', true),
('TKG', 'Bandar Lampung', 'Lampung', true),
('AMQ', 'Ambon', 'Maluku', true),
('TJS', 'Tanjung Selor', 'North Kalimantan', true),
('TRK', 'Tarakan', 'North Kalimantan', true),
('TTE', 'Ternate', 'North Maluku', true),
('MDC', 'Manado', 'North Sulawesi', true),
('KNO', 'Medan', 'North Sumatra', true),
('DJJ', 'Jayapura', 'Papua', true),
('PKU', 'Pekanbaru', 'Riau', true),
('BTH', 'Batam', 'Riau Islands', true),
('TNJ', 'Tanjung Pinang', 'Riau Islands', true),
('BDJ', 'Banjarmasin', 'South Kalimantan', true),
('UPG', 'Makassar', 'South Sulawesi', true),
('PLM', 'Palembang', 'South Sumatra', true),
('BDO', 'Bandung', 'West Java', true),
('CBN', 'Cirebon', 'West Java', true),
('TSY', 'Tasikmalaya', 'West Java', true),
('PNK', 'Pontianak', 'West Kalimantan', true),
('LOP', 'Mataram', 'West Nusa Tenggara', true),
('MKW', 'Manokwari', 'West Papua', true)
ON CONFLICT (city_code) DO NOTHING;