CREATE TABLE leave_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    min_duration_days INT,
    has_balance_quota BOOLEAN NOT NULL DEFAULT FALSE,
    is_paid_leave BOOLEAN NOT NULL DEFAULT FALSE,
    max_duration_days INT,
    requires_document BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL
);

-- Create indexes for better performance
CREATE INDEX idx_leave_types_code ON leave_types(code);
CREATE INDEX idx_leave_types_active ON leave_types(is_active);

-- Insert initial leave types according to Indonesian regulations with specific IDs
INSERT INTO leave_types (id, code, name, description, min_duration_days, has_balance_quota, is_paid_leave, max_duration_days, requires_document, is_active) VALUES
(1, 'ANNUAL_LEAVE', 'Cuti Tahunan', 'Cuti tahunan berbayar (bisa diajukan 1-12 hari)', 1, TRUE, TRUE, NULL, FALSE, TRUE),
(2, 'SICK_LEAVE', 'Cuti Sakit', 'Cuti sakit dengan surat keterangan dokter', 1, TRUE, TRUE, NULL, TRUE, TRUE),
(3, 'MATERNITY_LEAVE', 'Cuti Melahirkan', 'Cuti melahirkan 3 bulan (1.5 bulan sebelum dan 1.5 bulan sesudah)', 90, FALSE, TRUE, 90, TRUE, TRUE),
(4, 'MISCARRIAGE_LEAVE', 'Cuti Keguguran', 'Cuti keguguran 1.5 bulan', 45, FALSE, TRUE, 45, TRUE, TRUE),
(5, 'IMPORTANT_REASON_LEAVE', 'Cuti Alasan Penting', 'Cuti untuk alasan penting seperti menikah, anggota keluarga meninggal, dll', 1, FALSE, TRUE, 3, FALSE, TRUE),
(6, 'MENSTRUAL_LEAVE', 'Cuti Haid', 'Cuti haid 1-2 hari pertama', 1, FALSE, TRUE, 2, FALSE, TRUE),
(7, 'SABBATICAL_LEAVE', 'Cuti Besar', 'Cuti besar/istirahat panjang minimal 2 bulan setelah 6 tahun bekerja', 60, FALSE, TRUE, NULL, TRUE, TRUE),
(8, 'UNPAID_LEAVE', 'Cuti Tidak Berbayar', 'Cuti tanpa gaji untuk keperluan pribadi', 1, FALSE, FALSE, NULL, FALSE, TRUE),
(9, 'PATERNITY_LEAVE', 'Cuti Ayah', 'Cuti untuk ayah saat istri melahirkan', 1, FALSE, TRUE, 2, TRUE, TRUE),
(10, 'COMPASSIONATE_LEAVE', 'Cuti Belasungkawa', 'Cuti karena anggota keluarga meninggal', 1, FALSE, TRUE, 3, FALSE, TRUE);